CREATE TABLE products (
  id INTEGER GENERATED BY DEFAULT IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name varchar(50),
  description varchar(255),
  price decimal(15,2),
  PRIMARY KEY (id)
);